knowledge = ['Define', 'Identify', 'Describe', 'Label', 'List', 'Name', 'State', 'Match', 'Recognize', 'Select', 'Examine', 'Locate', 'Memorize', 'Quote', 'Recall', 'Reproduce', 'Tabulate', 'Tell', 'Copy', 'Discover', 'Duplicate', 'Enumerate', 'Listen', 'Observe', 'Omit', 'Read', 'Recite', 'Record', 'Repeat', 'Retell', 'Visualize']
understand = ['Explain', 'Describe', 'Interpret', 'Paraphrase', 'Summarize', 'Classify', 'Compare', 'Differentiate', 'Discuss', 'Distinguish', 'Extend', 'Predict', 'Associate', 'Contrast', 'Convert', 'Demonstrate', 'Estimate', 'Express', 'Identify', 'Indicate', 'Infer', 'Relate', 'Restate', 'Select', 'Translate', 'Ask', 'Cite', 'Discover', 'Generalize', 'Group', 'Illustrate', 'Judge', 'Observe', 'Order', 'Report', 'Represent', 'Research', 'Review', 'Rewrite', 'Show', 'Trace']
apply = ['Apply', 'Calculate', 'Choose', 'Compute', 'Construct', 'Demonstrate', 'Dramatize', 'Employ', 'Illustrate', 'Interpret', 'Manipulate', 'Modify', 'Operate', 'Practice', 'Prepare', 'Produce', 'Relate', 'Schedule', 'Show', 'Sketch', 'Solve', 'Use']
analyze = ['Analyze', 'Appraise', 'Categorize', 'Classify', 'Compare', 'Contrast', 'Criticize', 'Diagram', 'Differentiate', 'Discriminate', 'Distinguish', 'Divide', 'Examine', 'Infer', 'Outline', 'Point out', 'Question', 'Relate', 'Select', 'Separate', 'Subdivide', 'Test']
evaluate = ['Appraise', 'Argue', 'Assess', 'Choose', 'Compare', 'Conclude', 'Criticize', 'Critique', 'Defend', 'Estimate', 'Evaluate', 'Judge', 'Manage', 'Prepare', 'Rearrange', 'Reconcile', 'Set Up', 'Synthesize']
categories = {'knowledge': ['Define', 'Identify', 'Describe', 'Label', 'List', 'Name', 'State', 'Match', 'Recognize', 'Select', 'Examine', 'Locate', 'Memorize', 'Quote', 'Recall', 'Reproduce', 'Tabulate', 'Tell', 'Copy', 'Discover', 'Duplicate', 'Enumerate', 'Listen', 'Observe', 'Omit', 'Read', 'Recite', 'Record', 'Repeat', 'Retell', 'Visualize'], 'understand': ['Explain', 'Describe', 'Interpret', 'Paraphrase', 'Summarize', 'Classify', 'Compare', 'Differentiate', 'Discuss', 'Distinguish', 'Extend', 'Predict', 'Associate', 'Contrast', 'Convert', 'Demonstrate', 'Estimate', 'Express', 'Identify', 'Indicate', 'Infer', 'Relate', 'Restate', 'Select', 'Translate', 'Ask', 'Cite', 'Discover', 'Generalize', 'Group', 'Illustrate', 'Judge', 'Observe', 'Order', 'Report', 'Represent', 'Research', 'Review', 'Rewrite', 'Show', 'Trace'], 'apply': ['Apply', 'Calculate', 'Choose', 'Compute', 'Construct', 'Demonstrate', 'Dramatize', 'Employ', 'Illustrate', 'Interpret', 'Manipulate', 'Modify', 'Operate', 'Practice', 'Prepare', 'Produce', 'Relate', 'Schedule', 'Show', 'Sketch', 'Solve', 'Use'], 'analyze': ['Analyze', 'Appraise', 'Categorize', 'Classify', 'Compare', 'Contrast', 'Criticize', 'Diagram', 'Differentiate', 'Discriminate', 'Distinguish', 'Divide', 'Examine', 'Infer', 'Outline', 'Point out', 'Question', 'Relate', 'Select', 'Separate', 'Subdivide', 'Test'], 'evaluate': ['Appraise', 'Argue', 'Assess', 'Choose', 'Compare', 'Conclude', 'Criticize', 'Critique', 'Defend', 'Estimate', 'Evaluate', 'Judge', 'Manage', 'Prepare', 'Rearrange', 'Reconcile', 'Set Up', 'Synthesize']}
exclude_sections = {'index', 'glossary', 'title', 'introduction', 'preface', 'section', 'contents', 'appendix'}
learning_outcomes_templates = ['{} the main concepts of {} in the chapter.', '{} all key terms related to {} from the text.', '{} the difference between {} and other major theories.', '{} the historical events that led to {}.', '{} and explain the role of {} in the scientific method.', '{} the steps involved in the experiment on {}.', "{} the author's main arguments concerning {}.", '{} how to perform a basic analysis of {}.', '{} all figures that represent {} in the document.', '{} relevant data about {} using statistical tools.', '{} a simple experiment demonstrating the principles of {}.', '{} the correct sequence of events in the context of {}.', '{} important formulas related to {} during the review.', '{} and apply the techniques learned from {}.', '{} the outcomes of the study critically, focusing on {}.', '{} and categorize the samples collected from {}.', '{} key information during lectures about {} efficiently.', '{} diagrams and charts that illustrate {} effectively.', '{} facts from hypotheses about {} skillfully.']
adjectives = ["comprehensive", "advanced", "introductory", "detailed", "practical"]
nouns = ["basics", "concepts", "applications", "principles", "techniques"]
verbs = ["covers", "introduces", "explores", "discusses", "explains"]
templates = ["This {adjective} course {verb} the {noun} of {title}.", "Students will learn {noun} and {noun} in {topic}.", "The course {verb} key {noun} essential for {topic}.", "Explore {noun} through {adjective} {topic} lectures and hands-on projects.", "Gain {noun} in {topic} through {adjective} study and real-world {noun}."
]